// AUTO-GENERATED by scripts/genOfficialMap.ts — mapa oficial S/M/L exacto
// 6 islas: 2 small (7), 2 medium (9), 2 large (11) = 54 regiones
import type { RegionData } from './types'

export const REGIONS: RegionData[] = [
 {
  "id": "sa1",
  "name": "Cima del Vigía",
  "terrain": "mountains",
  "landmass": "small_a",
  "faction": "neutral",
  "mountain": true,
  "coastal": true,
  "polygon": [
   [
    104.5,
    50
   ],
   [
    270,
    50
   ],
   [
    229.57,
    151.09
   ],
   [
    168.71,
    141.72
   ]
  ],
  "center": [
   193.61,
   90.71
  ],
  "neighbors": [
   "sa2",
   "sa3",
   "sa4"
  ]
 },
 {
  "id": "sa2",
  "name": "Campos de Westfall",
  "terrain": "fields",
  "landmass": "small_a",
  "faction": "alliance",
  "landmark": "S",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    229.57,
    151.09
   ],
   [
    270,
    50
   ],
   [
    350,
    50
   ],
   [
    350,
    184.29
   ],
   [
    263.71,
    196.61
   ]
  ],
  "center": [
   297.95,
   123.23
  ],
  "neighbors": [
   "sa1",
   "sa4",
   "sa5"
  ]
 },
 {
  "id": "sa3",
  "name": "Colinas de Hillsbrad",
  "terrain": "hills",
  "landmass": "small_a",
  "faction": "neutral",
  "lostTribe": true,
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    50,
    50
   ],
   [
    104.5,
    50
   ],
   [
    168.71,
    141.72
   ],
   [
    106.25,
    225
   ],
   [
    50,
    225
   ]
  ],
  "center": [
   95.44,
   138.3
  ],
  "neighbors": [
   "sa1",
   "sa4",
   "sa6"
  ]
 },
 {
  "id": "sa4",
  "name": "Bosque de Elwynn",
  "terrain": "forest",
  "landmass": "small_a",
  "faction": "alliance",
  "mountain": false,
  "coastal": false,
  "polygon": [
   [
    106.25,
    225
   ],
   [
    168.71,
    141.72
   ],
   [
    229.57,
    151.09
   ],
   [
    263.71,
    196.61
   ],
   [
    236.29,
    273.39
   ],
   [
    171.15,
    282.69
   ]
  ],
  "center": [
   190.39,
   213.32
  ],
  "neighbors": [
   "sa1",
   "sa2",
   "sa3",
   "sa5",
   "sa6",
   "sa7"
  ]
 },
 {
  "id": "sa5",
  "name": "Montañas Crestagrana",
  "terrain": "mountains",
  "landmass": "small_a",
  "faction": "alliance",
  "mountain": true,
  "coastal": true,
  "polygon": [
   [
    236.29,
    273.39
   ],
   [
    263.71,
    196.61
   ],
   [
    350,
    184.29
   ],
   [
    350,
    400
   ],
   [
    331.25,
    400
   ]
  ],
  "center": [
   306.2,
   278.19
  ],
  "neighbors": [
   "sa2",
   "sa4",
   "sa7"
  ]
 },
 {
  "id": "sa6",
  "name": "Llanos de Mulgore",
  "terrain": "fields",
  "landmass": "small_a",
  "faction": "horde",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    50,
    225
   ],
   [
    106.25,
    225
   ],
   [
    171.15,
    282.69
   ],
   [
    112.5,
    400
   ],
   [
    50,
    400
   ]
  ],
  "center": [
   97.1,
   310.07
  ],
  "neighbors": [
   "sa3",
   "sa4",
   "sa7"
  ]
 },
 {
  "id": "sa7",
  "name": "Pantano de los Zánganos",
  "terrain": "swamp",
  "landmass": "small_a",
  "faction": "neutral",
  "lostTribe": true,
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    112.5,
    400
   ],
   [
    171.15,
    282.69
   ],
   [
    236.29,
    273.39
   ],
   [
    331.25,
    400
   ]
  ],
  "center": [
   215.8,
   349.82
  ],
  "neighbors": [
   "sa4",
   "sa5",
   "sa6"
  ]
 },
 {
  "id": "sb1",
  "name": "Montañas de Alterac",
  "terrain": "mountains",
  "landmass": "small_b",
  "mountain": true,
  "coastal": true,
  "polygon": [
   [
    450,
    50
   ],
   [
    638.33,
    50
   ],
   [
    619.25,
    121.56
   ],
   [
    564.2,
    144.5
   ],
   [
    450,
    73.12
   ]
  ],
  "center": [
   552.17,
   85.84
  ],
  "neighbors": [
   "sb2",
   "sb3",
   "sb4"
  ]
 },
 {
  "id": "sb2",
  "name": "Campos de Arathi",
  "terrain": "fields",
  "landmass": "small_b",
  "landmark": "S",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    619.25,
    121.56
   ],
   [
    638.33,
    50
   ],
   [
    750,
    50
   ],
   [
    750,
    184.29
   ],
   [
    677.69,
    194.62
   ]
  ],
  "center": [
   692.44,
   116.26
  ],
  "neighbors": [
   "sb1",
   "sb4",
   "sb5"
  ]
 },
 {
  "id": "sb3",
  "name": "Bosque de Argénteos",
  "terrain": "forest",
  "landmass": "small_b",
  "faction": "alliance",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    450,
    73.12
   ],
   [
    564.2,
    144.5
   ],
   [
    530,
    230
   ],
   [
    450,
    230
   ]
  ],
  "center": [
   495.43,
   163.66
  ],
  "neighbors": [
   "sb1",
   "sb4",
   "sb6"
  ]
 },
 {
  "id": "sb4",
  "name": "Claro de Tirisfal",
  "terrain": "forest",
  "landmass": "small_b",
  "lostTribe": true,
  "mountain": false,
  "coastal": false,
  "polygon": [
   [
    530,
    230
   ],
   [
    564.2,
    144.5
   ],
   [
    619.25,
    121.56
   ],
   [
    677.69,
    194.62
   ],
   [
    640,
    270
   ],
   [
    570,
    270
   ]
  ],
  "center": [
   603.47,
   203.44
  ],
  "neighbors": [
   "sb1",
   "sb2",
   "sb3",
   "sb5",
   "sb6",
   "sb7"
  ]
 },
 {
  "id": "sb5",
  "name": "Montañas de Colmillo",
  "terrain": "mountains",
  "landmass": "small_b",
  "mountain": true,
  "coastal": true,
  "polygon": [
   [
    640,
    270
   ],
   [
    677.69,
    194.62
   ],
   [
    750,
    184.29
   ],
   [
    750,
    400
   ],
   [
    726.67,
    400
   ]
  ],
  "center": [
   708.76,
   280.73
  ],
  "neighbors": [
   "sb2",
   "sb4",
   "sb7"
  ]
 },
 {
  "id": "sb6",
  "name": "Praderas de Loch Modan",
  "terrain": "fields",
  "landmass": "small_b",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    450,
    230
   ],
   [
    530,
    230
   ],
   [
    570,
    270
   ],
   [
    518,
    400
   ],
   [
    450,
    400
   ]
  ],
  "center": [
   498.81,
   309.85
  ],
  "neighbors": [
   "sb3",
   "sb4",
   "sb7"
  ]
 },
 {
  "id": "sb7",
  "name": "Ciénaga de Dustwallow",
  "terrain": "swamp",
  "landmass": "small_b",
  "lostTribe": true,
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    518,
    400
   ],
   [
    570,
    270
   ],
   [
    640,
    270
   ],
   [
    726.67,
    400
   ]
  ],
  "center": [
   615.11,
   345.78
  ],
  "neighbors": [
   "sb4",
   "sb5",
   "sb6"
  ]
 },
 {
  "id": "ma1",
  "name": "Pantano de las Penas",
  "terrain": "swamp",
  "landmass": "medium_a",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    50,
    450
   ],
   [
    230.33,
    450
   ],
   [
    216.9,
    550.71
   ],
   [
    50,
    488.12
   ]
  ],
  "center": [
   150.15,
   486.87
  ],
  "neighbors": [
   "ma2",
   "ma8"
  ]
 },
 {
  "id": "ma2",
  "name": "Campos de Trabalomas",
  "terrain": "fields",
  "landmass": "medium_a",
  "landmark": "M",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    216.9,
    550.71
   ],
   [
    230.33,
    450
   ],
   [
    400,
    450
   ],
   [
    400,
    493.13
   ],
   [
    269,
    575
   ],
   [
    242,
    575
   ],
   [
    220.53,
    561.58
   ]
  ],
  "center": [
   297.62,
   501.61
  ],
  "neighbors": [
   "ma1",
   "ma3",
   "ma4",
   "ma8",
   "ma9"
  ]
 },
 {
  "id": "ma3",
  "name": "Bosque de Terokkar",
  "terrain": "forest",
  "landmass": "medium_a",
  "faction": "neutral",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    269,
    575
   ],
   [
    400,
    493.13
   ],
   [
    400,
    668.57
   ]
  ],
  "center": [
   356.33,
   578.9
  ],
  "neighbors": [
   "ma2",
   "ma4"
  ]
 },
 {
  "id": "ma4",
  "name": "Caverna de Desolace",
  "terrain": "swamp",
  "landmass": "medium_a",
  "lostTribe": true,
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    242,
    575
   ],
   [
    269,
    575
   ],
   [
    400,
    668.57
   ],
   [
    400,
    686.15
   ],
   [
    275,
    734.23
   ],
   [
    256.5,
    720
   ]
  ],
  "center": [
   305.4,
   658.92
  ],
  "neighbors": [
   "ma2",
   "ma3",
   "ma5",
   "ma6",
   "ma9"
  ]
 },
 {
  "id": "ma5",
  "name": "Montañas de Cumbre Borrascosa",
  "terrain": "mountains",
  "landmass": "medium_a",
  "mountain": true,
  "coastal": true,
  "polygon": [
   [
    275,
    734.23
   ],
   [
    400,
    686.15
   ],
   [
    400,
    850
   ],
   [
    275,
    850
   ]
  ],
  "center": [
   341.08,
   779.41
  ],
  "neighbors": [
   "ma4",
   "ma6"
  ]
 },
 {
  "id": "ma6",
  "name": "Colinas de Feralas",
  "terrain": "hills",
  "landmass": "medium_a",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    50,
    850
   ],
   [
    180,
    720
   ],
   [
    256.5,
    720
   ],
   [
    275,
    734.23
   ],
   [
    275,
    850
   ]
  ],
  "center": [
   190.1,
   794.24
  ],
  "neighbors": [
   "ma4",
   "ma5",
   "ma7",
   "ma9"
  ]
 },
 {
  "id": "ma7",
  "name": "Bosque de Frondavil",
  "terrain": "forest",
  "landmass": "medium_a",
  "faction": "alliance",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    50,
    630
   ],
   [
    135,
    630
   ],
   [
    180,
    720
   ],
   [
    50,
    850
   ]
  ],
  "center": [
   99.31,
   717.86
  ],
  "neighbors": [
   "ma6",
   "ma8",
   "ma9"
  ]
 },
 {
  "id": "ma8",
  "name": "Praderas de Vallefresno",
  "terrain": "hills",
  "landmass": "medium_a",
  "lostTribe": true,
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    50,
    488.12
   ],
   [
    216.9,
    550.71
   ],
   [
    220.53,
    561.58
   ],
   [
    135,
    630
   ],
   [
    50,
    630
   ]
  ],
  "center": [
   114.85,
   567.28
  ],
  "neighbors": [
   "ma1",
   "ma2",
   "ma7",
   "ma9"
  ]
 },
 {
  "id": "ma9",
  "name": "Campos de Costasur",
  "terrain": "fields",
  "landmass": "medium_a",
  "mountain": false,
  "coastal": false,
  "polygon": [
   [
    135,
    630
   ],
   [
    220.53,
    561.58
   ],
   [
    242,
    575
   ],
   [
    256.5,
    720
   ],
   [
    180,
    720
   ]
  ],
  "center": [
   204.44,
   649.2
  ],
  "neighbors": [
   "ma2",
   "ma4",
   "ma6",
   "ma7",
   "ma8"
  ]
 },
 {
  "id": "mb1",
  "name": "Bosque de Ashenvale",
  "terrain": "forest",
  "landmass": "medium_b",
  "faction": "alliance",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    500,
    450
   ],
   [
    600,
    450
   ],
   [
    600,
    517.5
   ],
   [
    500,
    567.5
   ]
  ],
  "center": [
   545.5,
   497.38
  ],
  "neighbors": [
   "mb2",
   "mb5"
  ]
 },
 {
  "id": "mb2",
  "name": "Ciénaga de Marjal Revolcafango",
  "terrain": "swamp",
  "landmass": "medium_b",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    600,
    450
   ],
   [
    730.33,
    450
   ],
   [
    713.75,
    574.38
   ],
   [
    600,
    517.5
   ]
  ],
  "center": [
   667.4,
   498.69
  ],
  "neighbors": [
   "mb1",
   "mb3",
   "mb5"
  ]
 },
 {
  "id": "mb3",
  "name": "Campos de Vega de Tuercespina",
  "terrain": "fields",
  "landmass": "medium_b",
  "landmark": "M",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    713.75,
    574.38
   ],
   [
    730.33,
    450
   ],
   [
    900,
    450
   ],
   [
    900,
    493.13
   ],
   [
    745,
    590
   ],
   [
    720,
    590
   ]
  ],
  "center": [
   794.5,
   505.31
  ],
  "neighbors": [
   "mb2",
   "mb4",
   "mb5",
   "mb7"
  ]
 },
 {
  "id": "mb4",
  "name": "Montañas de Filospada",
  "terrain": "mountains",
  "landmass": "medium_b",
  "mountain": true,
  "coastal": true,
  "polygon": [
   [
    745,
    590
   ],
   [
    900,
    493.13
   ],
   [
    900,
    667.5
   ]
  ],
  "center": [
   848.33,
   583.54
  ],
  "neighbors": [
   "mb3",
   "mb7"
  ]
 },
 {
  "id": "mb5",
  "name": "Colinas de Desolace",
  "terrain": "hills",
  "landmass": "medium_b",
  "lostTribe": true,
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    500,
    567.5
   ],
   [
    600,
    517.5
   ],
   [
    713.75,
    574.38
   ],
   [
    720,
    590
   ],
   [
    707.5,
    615
   ],
   [
    500,
    615
   ]
  ],
  "center": [
   604.65,
   577.92
  ],
  "neighbors": [
   "mb1",
   "mb2",
   "mb3",
   "mb6",
   "mb7"
  ]
 },
 {
  "id": "mb6",
  "name": "Bosque de Vega Crepuscular",
  "terrain": "forest",
  "landmass": "medium_b",
  "lostTribe": true,
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    500,
    615
   ],
   [
    707.5,
    615
   ],
   [
    694.47,
    701.84
   ],
   [
    612.14,
    729.29
   ],
   [
    500,
    686.15
   ]
  ],
  "center": [
   603.65,
   663.12
  ],
  "neighbors": [
   "mb5",
   "mb7",
   "mb8",
   "mb9"
  ]
 },
 {
  "id": "mb7",
  "name": "Campos de los Baldíos Sur",
  "terrain": "fields",
  "landmass": "medium_b",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    694.47,
    701.84
   ],
   [
    707.5,
    615
   ],
   [
    720,
    590
   ],
   [
    745,
    590
   ],
   [
    900,
    667.5
   ],
   [
    900,
    850
   ],
   [
    813,
    850
   ]
  ],
  "center": [
   806.51,
   720.48
  ],
  "neighbors": [
   "mb3",
   "mb4",
   "mb5",
   "mb6",
   "mb9"
  ]
 },
 {
  "id": "mb8",
  "name": "Montañas de Sierra Espolón",
  "terrain": "mountains",
  "landmass": "medium_b",
  "mountain": true,
  "coastal": true,
  "polygon": [
   [
    500,
    686.15
   ],
   [
    612.14,
    729.29
   ],
   [
    588,
    850
   ],
   [
    500,
    850
   ]
  ],
  "center": [
   548.13,
   775.15
  ],
  "neighbors": [
   "mb6",
   "mb9"
  ]
 },
 {
  "id": "mb9",
  "name": "Bosque de Claro de la Luna",
  "terrain": "forest",
  "landmass": "medium_b",
  "faction": "neutral",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    588,
    850
   ],
   [
    612.14,
    729.29
   ],
   [
    694.47,
    701.84
   ],
   [
    813,
    850
   ]
  ],
  "center": [
   683.92,
   791.85
  ],
  "neighbors": [
   "mb6",
   "mb7",
   "mb8"
  ]
 },
 {
  "id": "la1",
  "name": "Pantano de Zangarmar",
  "terrain": "swamp",
  "landmass": "large_a",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    98,
    900
   ],
   [
    242.94,
    900
   ],
   [
    223.17,
    1012.04
   ],
   [
    155,
    995
   ]
  ],
  "center": [
   180.62,
   945.36
  ],
  "neighbors": [
   "la10",
   "la2",
   "la9"
  ]
 },
 {
  "id": "la2",
  "name": "Campos de Elwynn",
  "terrain": "fields",
  "landmass": "large_a",
  "landmark": "L",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    223.17,
    1012.04
   ],
   [
    242.94,
    900
   ],
   [
    450,
    900
   ],
   [
    450,
    925
   ],
   [
    328.85,
    1032.69
   ],
   [
    225.84,
    1017.98
   ]
  ],
  "center": [
   322.97,
   956.38
  ],
  "neighbors": [
   "la1",
   "la3",
   "la4",
   "la9"
  ]
 },
 {
  "id": "la3",
  "name": "Montañas de Dun Morogh",
  "terrain": "mountains",
  "landmass": "large_a",
  "mountain": true,
  "coastal": true,
  "polygon": [
   [
    328.85,
    1032.69
   ],
   [
    450,
    925
   ],
   [
    450,
    1115
   ],
   [
    370,
    1115
   ]
  ],
  "center": [
   403.69,
   1038.32
  ],
  "neighbors": [
   "la2",
   "la4",
   "la5"
  ]
 },
 {
  "id": "la4",
  "name": "Colinas de Loch Modan",
  "terrain": "hills",
  "landmass": "large_a",
  "faction": "alliance",
  "mountain": false,
  "coastal": false,
  "polygon": [
   [
    223.46,
    1026.54
   ],
   [
    225.84,
    1017.98
   ],
   [
    328.85,
    1032.69
   ],
   [
    370,
    1115
   ],
   [
    296.25,
    1207.19
   ],
   [
    278.95,
    1211.51
   ]
  ],
  "center": [
   295.14,
   1102.16
  ],
  "neighbors": [
   "la11",
   "la2",
   "la3",
   "la5",
   "la6",
   "la9"
  ]
 },
 {
  "id": "la5",
  "name": "Campos de Westfall",
  "terrain": "fields",
  "landmass": "large_a",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    296.25,
    1207.19
   ],
   [
    370,
    1115
   ],
   [
    450,
    1115
   ],
   [
    450,
    1271.25
   ]
  ],
  "center": [
   392.49,
   1185.58
  ],
  "neighbors": [
   "la3",
   "la4",
   "la6"
  ]
 },
 {
  "id": "la6",
  "name": "Montañas de Crestagrana",
  "terrain": "mountains",
  "landmass": "large_a",
  "mountain": true,
  "coastal": true,
  "polygon": [
   [
    239,
    1400
   ],
   [
    255.81,
    1231.94
   ],
   [
    278.95,
    1211.51
   ],
   [
    296.25,
    1207.19
   ],
   [
    450,
    1271.25
   ],
   [
    450,
    1400
   ]
  ],
  "center": [
   342.81,
   1317.3
  ],
  "neighbors": [
   "la11",
   "la4",
   "la5",
   "la7"
  ]
 },
 {
  "id": "la7",
  "name": "Bosque de Tuercespina",
  "terrain": "forest",
  "landmass": "large_a",
  "lostTribe": true,
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    50,
    1255.5
   ],
   [
    195.53,
    1211.84
   ],
   [
    255.81,
    1231.94
   ],
   [
    239,
    1400
   ],
   [
    50,
    1400
   ]
  ],
  "center": [
   152.46,
   1313.43
  ],
  "neighbors": [
   "la11",
   "la6",
   "la8"
  ]
 },
 {
  "id": "la8",
  "name": "Montañas de Vega de Tuercespina",
  "terrain": "mountains",
  "landmass": "large_a",
  "mountain": true,
  "coastal": true,
  "polygon": [
   [
    50,
    1115
   ],
   [
    135,
    1115
   ],
   [
    195.53,
    1211.84
   ],
   [
    50,
    1255.5
   ]
  ],
  "center": [
   106.64,
   1180.67
  ],
  "neighbors": [
   "la11",
   "la7",
   "la9"
  ]
 },
 {
  "id": "la9",
  "name": "Praderas de Mulgore",
  "terrain": "hills",
  "landmass": "large_a",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    50,
    1018.33
   ],
   [
    155,
    995
   ],
   [
    223.17,
    1012.04
   ],
   [
    225.84,
    1017.98
   ],
   [
    223.46,
    1026.54
   ],
   [
    135,
    1115
   ],
   [
    50,
    1115
   ]
  ],
  "center": [
   123.72,
   1053.4
  ],
  "neighbors": [
   "la1",
   "la10",
   "la11",
   "la2",
   "la4",
   "la8"
  ]
 },
 {
  "id": "la10",
  "name": "Bosque de Claros de Tirisfal",
  "terrain": "forest",
  "landmass": "large_a",
  "faction": "horde",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    50,
    900
   ],
   [
    98,
    900
   ],
   [
    155,
    995
   ],
   [
    50,
    1018.33
   ]
  ],
  "center": [
   89.3,
   960.52
  ],
  "neighbors": [
   "la1",
   "la9"
  ]
 },
 {
  "id": "la11",
  "name": "Ciénaga de las Mil Agujas",
  "terrain": "swamp",
  "landmass": "large_a",
  "lostTribe": true,
  "mountain": false,
  "coastal": false,
  "polygon": [
   [
    135,
    1115
   ],
   [
    223.46,
    1026.54
   ],
   [
    278.95,
    1211.51
   ],
   [
    255.81,
    1231.94
   ],
   [
    195.53,
    1211.84
   ]
  ],
  "center": [
   211.73,
   1139.29
  ],
  "neighbors": [
   "la4",
   "la6",
   "la7",
   "la8",
   "la9"
  ]
 },
 {
  "id": "lb1",
  "name": "Bosque de Cuna del Invierno",
  "terrain": "forest",
  "landmass": "large_b",
  "faction": "neutral",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    550,
    900
   ],
   [
    650,
    900
   ],
   [
    650,
    990
   ],
   [
    592.14,
    1038.21
   ],
   [
    550,
    1048.75
   ]
  ],
  "center": [
   595.98,
   964.53
  ],
  "neighbors": [
   "lb2",
   "lb5",
   "lb6"
  ]
 },
 {
  "id": "lb2",
  "name": "Pantano de Feralas",
  "terrain": "swamp",
  "landmass": "large_b",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    650,
    900
   ],
   [
    784,
    900
   ],
   [
    766,
    990
   ],
   [
    650,
    990
   ]
  ],
  "center": [
   712.61,
   943.92
  ],
  "neighbors": [
   "lb1",
   "lb3",
   "lb5"
  ]
 },
 {
  "id": "lb3",
  "name": "Campos de Tanaris",
  "terrain": "fields",
  "landmass": "large_b",
  "landmark": "L",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    766,
    990
   ],
   [
    784,
    900
   ],
   [
    950,
    900
   ],
   [
    950,
    963.33
   ],
   [
    800,
    1046.67
   ]
  ],
  "center": [
   851.93,
   957.4
  ],
  "neighbors": [
   "lb2",
   "lb4",
   "lb5"
  ]
 },
 {
  "id": "lb4",
  "name": "Montañas de Cuna del Invierno",
  "terrain": "mountains",
  "landmass": "large_b",
  "mountain": true,
  "coastal": true,
  "polygon": [
   [
    800,
    1046.67
   ],
   [
    950,
    963.33
   ],
   [
    950,
    1143.85
   ],
   [
    803.09,
    1087.34
   ],
   [
    800,
    1075
   ]
  ],
  "center": [
   891.12,
   1058.61
  ],
  "neighbors": [
   "lb10",
   "lb3",
   "lb5",
   "lb7"
  ]
 },
 {
  "id": "lb5",
  "name": "Colinas de Silithus",
  "terrain": "hills",
  "landmass": "large_b",
  "lostTribe": true,
  "mountain": false,
  "coastal": false,
  "polygon": [
   [
    592.14,
    1038.21
   ],
   [
    650,
    990
   ],
   [
    766,
    990
   ],
   [
    800,
    1046.67
   ],
   [
    800,
    1075
   ],
   [
    651,
    1075
   ]
  ],
  "center": [
   704.51,
   1034.39
  ],
  "neighbors": [
   "lb1",
   "lb10",
   "lb2",
   "lb3",
   "lb4",
   "lb6"
  ]
 },
 {
  "id": "lb6",
  "name": "Bosque de Frondavil",
  "terrain": "forest",
  "landmass": "large_b",
  "lostTribe": true,
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    550,
    1048.75
   ],
   [
    592.14,
    1038.21
   ],
   [
    651,
    1075
   ],
   [
    723,
    1195
   ],
   [
    665,
    1195
   ],
   [
    550,
    1080
   ]
  ],
  "center": [
   631.3,
   1115.72
  ],
  "neighbors": [
   "lb1",
   "lb10",
   "lb5",
   "lb8",
   "lb9"
  ]
 },
 {
  "id": "lb7",
  "name": "Campos de Vega de Tuercespina Sur",
  "terrain": "fields",
  "landmass": "large_b",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    742.43,
    1201.07
   ],
   [
    803.09,
    1087.34
   ],
   [
    950,
    1143.85
   ],
   [
    950,
    1292.08
   ],
   [
    744.6,
    1206.5
   ]
  ],
  "center": [
   860.56,
   1186.2
  ],
  "neighbors": [
   "lb10",
   "lb11",
   "lb4",
   "lb9"
  ]
 },
 {
  "id": "lb8",
  "name": "Montañas de Silithus",
  "terrain": "mountains",
  "landmass": "large_b",
  "mountain": true,
  "coastal": true,
  "polygon": [
   [
    550,
    1080
   ],
   [
    665,
    1195
   ],
   [
    550,
    1266.88
   ]
  ],
  "center": [
   588.33,
   1180.63
  ],
  "neighbors": [
   "lb6",
   "lb9"
  ]
 },
 {
  "id": "lb9",
  "name": "Bosque de Claro de la Luna Sur",
  "terrain": "forest",
  "landmass": "large_b",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    550,
    1266.88
   ],
   [
    665,
    1195
   ],
   [
    723,
    1195
   ],
   [
    742.43,
    1201.07
   ],
   [
    744.6,
    1206.5
   ],
   [
    693,
    1400
   ],
   [
    550,
    1400
   ]
  ],
  "center": [
   641.98,
   1302.15
  ],
  "neighbors": [
   "lb10",
   "lb11",
   "lb6",
   "lb7",
   "lb8"
  ]
 },
 {
  "id": "lb10",
  "name": "Pantano de Dustwallow",
  "terrain": "swamp",
  "landmass": "large_b",
  "lostTribe": true,
  "mountain": false,
  "coastal": false,
  "polygon": [
   [
    651,
    1075
   ],
   [
    800,
    1075
   ],
   [
    803.09,
    1087.34
   ],
   [
    742.43,
    1201.07
   ],
   [
    723,
    1195
   ]
  ],
  "center": [
   731.47,
   1120.71
  ],
  "neighbors": [
   "lb4",
   "lb5",
   "lb6",
   "lb7",
   "lb9"
  ]
 },
 {
  "id": "lb11",
  "name": "Montañas de Tanaris",
  "terrain": "mountains",
  "landmass": "large_b",
  "mountain": true,
  "coastal": true,
  "polygon": [
   [
    693,
    1400
   ],
   [
    744.6,
    1206.5
   ],
   [
    950,
    1292.08
   ],
   [
    950,
    1400
   ]
  ],
  "center": [
   822.28,
   1324.41
  ],
  "neighbors": [
   "lb7",
   "lb9"
  ]
 }
]
