// AUTO-GENERATED by scripts/genmap.ts — do not edit by hand.
import type { RegionData } from './types'

export const REGIONS: RegionData[] = [
 {
  "id": "teldrassil",
  "name": "Teldrassil",
  "terrain": "forest",
  "landmass": "teldrassil",
  "faction": "alliance",
  "landmark": "Darnassus",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    92,
    132
   ],
   [
    96,
    96
   ],
   [
    130,
    86
   ],
   [
    160,
    100
   ],
   [
    166,
    130
   ],
   [
    148,
    156
   ],
   [
    114,
    158
   ]
  ],
  "center": [
   128.31,
   122.42
  ],
  "neighbors": []
 },
 {
  "id": "darkshore",
  "name": "Darkshore",
  "terrain": "forest",
  "landmass": "kalimdor",
  "faction": "alliance",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    146,
    168
   ],
   [
    166,
    122
   ],
   [
    196,
    96
   ],
   [
    199.53,
    95.12
   ],
   [
    222.53,
    155.9
   ],
   [
    149.25,
    208.66
   ]
  ],
  "center": [
   181.5,
   151.21
  ],
  "neighbors": [
   "felwood",
   "moonglade"
  ]
 },
 {
  "id": "moonglade",
  "name": "Moonglade",
  "terrain": "forest",
  "landmass": "kalimdor",
  "faction": "neutral",
  "landmark": "Nighthaven",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    199.53,
    95.12
   ],
   [
    244,
    84
   ],
   [
    286,
    104
   ],
   [
    298.2,
    121.83
   ],
   [
    251.86,
    170.19
   ],
   [
    222.53,
    155.9
   ]
  ],
  "center": [
   246.99,
   122.99
  ],
  "neighbors": [
   "darkshore",
   "felwood",
   "winterspring"
  ]
 },
 {
  "id": "winterspring",
  "name": "Winterspring",
  "terrain": "mountains",
  "landmass": "kalimdor",
  "lostTribe": true,
  "mountain": true,
  "coastal": true,
  "polygon": [
   [
    251.86,
    170.19
   ],
   [
    298.2,
    121.83
   ],
   [
    312,
    142
   ],
   [
    330,
    186
   ],
   [
    321.99,
    212.69
   ],
   [
    256.8,
    183.46
   ]
  ],
  "center": [
   294.73,
   170.52
  ],
  "neighbors": [
   "felwood",
   "hyjal",
   "moonglade"
  ]
 },
 {
  "id": "felwood",
  "name": "Felwood",
  "terrain": "forest",
  "landmass": "kalimdor",
  "lostTribe": true,
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    141.25,
    238.99
   ],
   [
    150,
    218
   ],
   [
    149.25,
    208.66
   ],
   [
    222.53,
    155.9
   ],
   [
    251.86,
    170.19
   ],
   [
    256.8,
    183.46
   ],
   [
    233.82,
    236.49
   ]
  ],
  "center": [
   204.46,
   204.1
  ],
  "neighbors": [
   "ashenvale",
   "darkshore",
   "hyjal",
   "moonglade",
   "winterspring"
  ]
 },
 {
  "id": "hyjal",
  "name": "Mount Hyjal",
  "terrain": "mountains",
  "landmass": "kalimdor",
  "landmark": "Nordrassil",
  "mountain": true,
  "coastal": true,
  "polygon": [
   [
    233.82,
    236.49
   ],
   [
    256.8,
    183.46
   ],
   [
    321.99,
    212.69
   ],
   [
    318.85,
    223.17
   ],
   [
    269.49,
    279.59
   ]
  ],
  "center": [
   274.24,
   228.25
  ],
  "neighbors": [
   "ashenvale",
   "azshara",
   "felwood",
   "winterspring"
  ]
 },
 {
  "id": "azshara",
  "name": "Azshara",
  "terrain": "hills",
  "landmass": "kalimdor",
  "faction": "horde",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    269.49,
    279.59
   ],
   [
    318.85,
    223.17
   ],
   [
    318,
    226
   ],
   [
    336,
    262
   ],
   [
    350.86,
    302.87
   ],
   [
    282.81,
    298.75
   ],
   [
    270,
    288.63
   ]
  ],
  "center": [
   310.62,
   273.52
  ],
  "neighbors": [
   "ashenvale",
   "durotar",
   "hyjal",
   "nbarrens"
  ]
 },
 {
  "id": "ashenvale",
  "name": "Ashenvale",
  "terrain": "forest",
  "landmass": "kalimdor",
  "faction": "neutral",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    133.07,
    258.62
   ],
   [
    141.25,
    238.99
   ],
   [
    233.82,
    236.49
   ],
   [
    269.49,
    279.59
   ],
   [
    270,
    288.63
   ],
   [
    222.9,
    319.58
   ]
  ],
  "center": [
   206.21,
   270.59
  ],
  "neighbors": [
   "azshara",
   "felwood",
   "hyjal",
   "nbarrens",
   "stonetalon"
  ]
 },
 {
  "id": "durotar",
  "name": "Durotar",
  "terrain": "wasteland",
  "landmass": "kalimdor",
  "faction": "horde",
  "landmark": "Orgrimmar",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    282.81,
    298.75
   ],
   [
    350.86,
    302.87
   ],
   [
    352,
    306
   ],
   [
    346,
    352
   ],
   [
    333.97,
    381.42
   ],
   [
    295.69,
    370.89
   ]
  ],
  "center": [
   318.23,
   335.5
  ],
  "neighbors": [
   "azshara",
   "nbarrens",
   "sbarrens"
  ]
 },
 {
  "id": "stonetalon",
  "name": "Stonetalon Mountains",
  "terrain": "mountains",
  "landmass": "kalimdor",
  "mountain": true,
  "coastal": true,
  "polygon": [
   [
    130,
    266
   ],
   [
    133.07,
    258.62
   ],
   [
    222.9,
    319.58
   ],
   [
    214.84,
    367.96
   ],
   [
    203.25,
    375.07
   ],
   [
    155.08,
    361.31
   ],
   [
    158,
    356
   ],
   [
    140,
    312
   ]
  ],
  "center": [
   176.67,
   323.32
  ],
  "neighbors": [
   "ashenvale",
   "desolace",
   "mulgore",
   "nbarrens"
  ]
 },
 {
  "id": "nbarrens",
  "name": "Northern Barrens",
  "terrain": "fields",
  "landmass": "kalimdor",
  "faction": "horde",
  "mountain": false,
  "coastal": false,
  "polygon": [
   [
    214.84,
    367.96
   ],
   [
    222.9,
    319.58
   ],
   [
    270,
    288.63
   ],
   [
    282.81,
    298.75
   ],
   [
    295.69,
    370.89
   ],
   [
    262.2,
    387.16
   ]
  ],
  "center": [
   256.95,
   341.88
  ],
  "neighbors": [
   "ashenvale",
   "azshara",
   "durotar",
   "mulgore",
   "sbarrens",
   "stonetalon"
  ]
 },
 {
  "id": "desolace",
  "name": "Desolace",
  "terrain": "wasteland",
  "landmass": "kalimdor",
  "lostTribe": true,
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    136,
    396
   ],
   [
    155.08,
    361.31
   ],
   [
    203.25,
    375.07
   ],
   [
    189.23,
    432.74
   ],
   [
    146.46,
    442.87
   ],
   [
    146,
    442
   ]
  ],
  "center": [
   168,
   401.53
  ],
  "neighbors": [
   "feralas",
   "mulgore",
   "stonetalon"
  ]
 },
 {
  "id": "mulgore",
  "name": "Mulgore",
  "terrain": "fields",
  "landmass": "kalimdor",
  "faction": "horde",
  "landmark": "Thunder Bluff",
  "mountain": false,
  "coastal": false,
  "polygon": [
   [
    189.23,
    432.74
   ],
   [
    203.25,
    375.07
   ],
   [
    214.84,
    367.96
   ],
   [
    262.2,
    387.16
   ],
   [
    266.24,
    451.88
   ],
   [
    225.52,
    467.77
   ]
  ],
  "center": [
   229.58,
   418.13
  ],
  "neighbors": [
   "desolace",
   "feralas",
   "nbarrens",
   "sbarrens",
   "stonetalon",
   "thousandneedles"
  ]
 },
 {
  "id": "sbarrens",
  "name": "Southern Barrens",
  "terrain": "fields",
  "landmass": "kalimdor",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    262.2,
    387.16
   ],
   [
    295.69,
    370.89
   ],
   [
    333.97,
    381.42
   ],
   [
    328,
    396
   ],
   [
    342.12,
    427.38
   ],
   [
    276.25,
    455.61
   ],
   [
    266.24,
    451.88
   ]
  ],
  "center": [
   297.31,
   411.61
  ],
  "neighbors": [
   "durotar",
   "dustwallow",
   "mulgore",
   "nbarrens",
   "thousandneedles"
  ]
 },
 {
  "id": "dustwallow",
  "name": "Dustwallow Marsh",
  "terrain": "swamp",
  "landmass": "kalimdor",
  "faction": "alliance",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    276.25,
    455.61
   ],
   [
    342.12,
    427.38
   ],
   [
    346,
    436
   ],
   [
    352,
    486
   ],
   [
    330,
    534
   ],
   [
    323.15,
    543.14
   ]
  ],
  "center": [
   320.53,
   477.98
  ],
  "neighbors": [
   "sbarrens",
   "thousandneedles"
  ]
 },
 {
  "id": "feralas",
  "name": "Feralas",
  "terrain": "forest",
  "landmass": "kalimdor",
  "lostTribe": true,
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    143.14,
    508.13
   ],
   [
    166,
    480
   ],
   [
    146.46,
    442.87
   ],
   [
    189.23,
    432.74
   ],
   [
    225.52,
    467.77
   ],
   [
    212.87,
    514.13
   ],
   [
    207.4,
    517.06
   ]
  ],
  "center": [
   186.13,
   476.76
  ],
  "neighbors": [
   "desolace",
   "mulgore",
   "silithus",
   "thousandneedles",
   "ungoro"
  ]
 },
 {
  "id": "thousandneedles",
  "name": "Thousand Needles",
  "terrain": "hills",
  "landmass": "kalimdor",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    212.87,
    514.13
   ],
   [
    225.52,
    467.77
   ],
   [
    266.24,
    451.88
   ],
   [
    276.25,
    455.61
   ],
   [
    323.15,
    543.14
   ],
   [
    314.12,
    555.18
   ],
   [
    284.7,
    557.67
   ]
  ],
  "center": [
   266.69,
   507.09
  ],
  "neighbors": [
   "dustwallow",
   "feralas",
   "mulgore",
   "sbarrens",
   "tanaris",
   "ungoro"
  ]
 },
 {
  "id": "silithus",
  "name": "Silithus",
  "terrain": "wasteland",
  "landmass": "kalimdor",
  "landmark": "Ahn’Qiraj",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    126,
    556
   ],
   [
    140,
    512
   ],
   [
    143.14,
    508.13
   ],
   [
    207.4,
    517.06
   ],
   [
    177.42,
    613.66
   ],
   [
    171.49,
    616.13
   ],
   [
    148,
    596
   ]
  ],
  "center": [
   165.15,
   554.25
  ],
  "neighbors": [
   "feralas",
   "uldum",
   "ungoro"
  ]
 },
 {
  "id": "ungoro",
  "name": "Un'Goro Crater",
  "terrain": "forest",
  "landmass": "kalimdor",
  "lostTribe": true,
  "mountain": false,
  "coastal": false,
  "polygon": [
   [
    177.42,
    613.66
   ],
   [
    207.4,
    517.06
   ],
   [
    212.87,
    514.13
   ],
   [
    284.7,
    557.67
   ],
   [
    222.77,
    617.22
   ]
  ],
  "center": [
   224.85,
   569.65
  ],
  "neighbors": [
   "feralas",
   "silithus",
   "tanaris",
   "thousandneedles",
   "uldum"
  ]
 },
 {
  "id": "tanaris",
  "name": "Tanaris",
  "terrain": "wasteland",
  "landmass": "kalimdor",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    222.77,
    617.22
   ],
   [
    284.7,
    557.67
   ],
   [
    314.12,
    555.18
   ],
   [
    306,
    566
   ],
   [
    312,
    612
   ],
   [
    292,
    664
   ],
   [
    277.59,
    680.81
   ]
  ],
  "center": [
   275.44,
   614.8
  ],
  "neighbors": [
   "thousandneedles",
   "uldum",
   "ungoro"
  ]
 },
 {
  "id": "uldum",
  "name": "Uldum",
  "terrain": "wasteland",
  "landmass": "kalimdor",
  "landmark": "Halls of Origination",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    162,
    664
   ],
   [
    176,
    620
   ],
   [
    171.49,
    616.13
   ],
   [
    177.42,
    613.66
   ],
   [
    222.77,
    617.22
   ],
   [
    277.59,
    680.81
   ],
   [
    256,
    706
   ],
   [
    214,
    726
   ],
   [
    178,
    706
   ]
  ],
  "center": [
   213.56,
   669.4
  ],
  "neighbors": [
   "silithus",
   "tanaris",
   "ungoro"
  ]
 },
 {
  "id": "queldanas",
  "name": "Isle of Quel'Danas",
  "terrain": "fields",
  "landmass": "quel-danas",
  "landmark": "Sunwell",
  "lostTribe": true,
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    796,
    102
   ],
   [
    800,
    72
   ],
   [
    834,
    66
   ],
   [
    856,
    84
   ],
   [
    850,
    110
   ],
   [
    820,
    120
   ]
  ],
  "center": [
   825.26,
   92.1
  ],
  "neighbors": []
 },
 {
  "id": "tirisfal",
  "name": "Tirisfal Glades",
  "terrain": "forest",
  "landmass": "eastern-kingdoms",
  "faction": "horde",
  "landmark": "Undercity",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    668.57,
    165.02
   ],
   [
    676,
    126
   ],
   [
    700,
    96
   ],
   [
    746,
    86
   ],
   [
    748.72,
    86.62
   ],
   [
    751.33,
    145.33
   ],
   [
    705.74,
    178.14
   ]
  ],
  "center": [
   712.69,
   132.35
  ],
  "neighbors": [
   "eversong",
   "silverpine",
   "wplaguelands"
  ]
 },
 {
  "id": "eversong",
  "name": "Eversong Woods",
  "terrain": "forest",
  "landmass": "eastern-kingdoms",
  "faction": "horde",
  "landmark": "Silvermoon",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    748.72,
    86.62
   ],
   [
    790,
    96
   ],
   [
    828,
    122
   ],
   [
    844.79,
    157.45
   ],
   [
    775.41,
    169.41
   ],
   [
    751.33,
    145.33
   ]
  ],
  "center": [
   789.28,
   131.4
  ],
  "neighbors": [
   "ghostlands",
   "tirisfal",
   "wplaguelands"
  ]
 },
 {
  "id": "ghostlands",
  "name": "Ghostlands",
  "terrain": "forest",
  "landmass": "eastern-kingdoms",
  "lostTribe": true,
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    771.93,
    225.2
   ],
   [
    775.41,
    169.41
   ],
   [
    844.79,
    157.45
   ],
   [
    846,
    160
   ],
   [
    860,
    204
   ],
   [
    857.08,
    216.85
   ],
   [
    772.69,
    225.89
   ]
  ],
  "center": [
   814.43,
   193.25
  ],
  "neighbors": [
   "alterac",
   "eplaguelands",
   "eversong",
   "wplaguelands"
  ]
 },
 {
  "id": "wplaguelands",
  "name": "Western Plaguelands",
  "terrain": "fields",
  "landmass": "eastern-kingdoms",
  "mountain": false,
  "coastal": false,
  "polygon": [
   [
    705.74,
    178.14
   ],
   [
    751.33,
    145.33
   ],
   [
    775.41,
    169.41
   ],
   [
    771.93,
    225.2
   ],
   [
    720.29,
    226.63
   ]
  ],
  "center": [
   743.85,
   190.66
  ],
  "neighbors": [
   "alterac",
   "eversong",
   "ghostlands",
   "silverpine",
   "tirisfal"
  ]
 },
 {
  "id": "eplaguelands",
  "name": "Eastern Plaguelands",
  "terrain": "wasteland",
  "landmass": "eastern-kingdoms",
  "lostTribe": true,
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    772.69,
    225.89
   ],
   [
    857.08,
    216.85
   ],
   [
    850,
    248
   ],
   [
    858.08,
    273.38
   ],
   [
    782.5,
    281.48
   ]
  ],
  "center": [
   815.66,
   249.03
  ],
  "neighbors": [
   "alterac",
   "ghostlands",
   "hinterlands"
  ]
 },
 {
  "id": "silverpine",
  "name": "Silverpine Forest",
  "terrain": "forest",
  "landmass": "eastern-kingdoms",
  "faction": "horde",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    646.25,
    247.04
   ],
   [
    652,
    214
   ],
   [
    668,
    168
   ],
   [
    668.57,
    165.02
   ],
   [
    705.74,
    178.14
   ],
   [
    720.29,
    226.63
   ],
   [
    705.29,
    243.85
   ]
  ],
  "center": [
   682.88,
   211.47
  ],
  "neighbors": [
   "alterac",
   "hillsbrad",
   "tirisfal",
   "wplaguelands"
  ]
 },
 {
  "id": "alterac",
  "name": "Alterac Mountains",
  "terrain": "mountains",
  "landmass": "eastern-kingdoms",
  "mountain": true,
  "coastal": false,
  "polygon": [
   [
    705.29,
    243.85
   ],
   [
    720.29,
    226.63
   ],
   [
    771.93,
    225.2
   ],
   [
    772.69,
    225.89
   ],
   [
    782.5,
    281.48
   ],
   [
    774.87,
    294.3
   ],
   [
    723.73,
    297.31
   ]
  ],
  "center": [
   745.63,
   260.53
  ],
  "neighbors": [
   "arathi",
   "eplaguelands",
   "ghostlands",
   "hillsbrad",
   "hinterlands",
   "silverpine",
   "wplaguelands"
  ]
 },
 {
  "id": "hillsbrad",
  "name": "Hillsbrad Foothills",
  "terrain": "fields",
  "landmass": "eastern-kingdoms",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    644,
    260
   ],
   [
    646.25,
    247.04
   ],
   [
    705.29,
    243.85
   ],
   [
    723.73,
    297.31
   ],
   [
    701,
    326.67
   ],
   [
    649.93,
    292.62
   ]
  ],
  "center": [
   684.08,
   279.68
  ],
  "neighbors": [
   "alterac",
   "arathi",
   "gilneas",
   "silverpine"
  ]
 },
 {
  "id": "hinterlands",
  "name": "The Hinterlands",
  "terrain": "forest",
  "landmass": "eastern-kingdoms",
  "lostTribe": true,
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    774.87,
    294.3
   ],
   [
    782.5,
    281.48
   ],
   [
    858.08,
    273.38
   ],
   [
    864,
    292
   ],
   [
    852,
    342
   ],
   [
    851.94,
    342.11
   ],
   [
    791.82,
    343.73
   ]
  ],
  "center": [
   821.14,
   308.42
  ],
  "neighbors": [
   "alterac",
   "arathi",
   "eplaguelands",
   "twilighthighlands"
  ]
 },
 {
  "id": "arathi",
  "name": "Arathi Highlands",
  "terrain": "hills",
  "landmass": "eastern-kingdoms",
  "mountain": false,
  "coastal": false,
  "polygon": [
   [
    701,
    326.67
   ],
   [
    723.73,
    297.31
   ],
   [
    774.87,
    294.3
   ],
   [
    791.82,
    343.73
   ],
   [
    772.77,
    371.17
   ],
   [
    738.29,
    376.66
   ],
   [
    701,
    340.66
   ]
  ],
  "center": [
   747.42,
   333.89
  ],
  "neighbors": [
   "alterac",
   "gilneas",
   "hillsbrad",
   "hinterlands",
   "lochmodan",
   "twilighthighlands",
   "wetlands"
  ]
 },
 {
  "id": "gilneas",
  "name": "Gilneas",
  "terrain": "forest",
  "landmass": "eastern-kingdoms",
  "faction": "alliance",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    628,
    344
   ],
   [
    652,
    304
   ],
   [
    649.93,
    292.62
   ],
   [
    701,
    326.67
   ],
   [
    701,
    340.66
   ],
   [
    634.94,
    383.93
   ]
  ],
  "center": [
   660.86,
   338.61
  ],
  "neighbors": [
   "arathi",
   "hillsbrad",
   "wetlands"
  ]
 },
 {
  "id": "twilighthighlands",
  "name": "Twilight Highlands",
  "terrain": "mountains",
  "landmass": "eastern-kingdoms",
  "mountain": true,
  "coastal": true,
  "polygon": [
   [
    772.77,
    371.17
   ],
   [
    791.82,
    343.73
   ],
   [
    851.94,
    342.11
   ],
   [
    830,
    380
   ],
   [
    846,
    420
   ],
   [
    847.08,
    433.53
   ],
   [
    801.06,
    414.36
   ]
  ],
  "center": [
   813.81,
   380.63
  ],
  "neighbors": [
   "arathi",
   "badlands",
   "hinterlands",
   "lochmodan"
  ]
 },
 {
  "id": "wetlands",
  "name": "Wetlands",
  "terrain": "swamp",
  "landmass": "eastern-kingdoms",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    634.94,
    383.93
   ],
   [
    701,
    340.66
   ],
   [
    738.29,
    376.66
   ],
   [
    717.66,
    424.79
   ],
   [
    648.63,
    414.01
   ],
   [
    636,
    390
   ]
  ],
  "center": [
   689.3,
   386.99
  ],
  "neighbors": [
   "arathi",
   "dunmorogh",
   "gilneas",
   "lochmodan"
  ]
 },
 {
  "id": "lochmodan",
  "name": "Loch Modan",
  "terrain": "hills",
  "landmass": "eastern-kingdoms",
  "mountain": false,
  "coastal": false,
  "polygon": [
   [
    717.66,
    424.79
   ],
   [
    738.29,
    376.66
   ],
   [
    772.77,
    371.17
   ],
   [
    801.06,
    414.36
   ],
   [
    753.87,
    453.22
   ],
   [
    726.79,
    446.26
   ]
  ],
  "center": [
   756.28,
   412.1
  ],
  "neighbors": [
   "arathi",
   "badlands",
   "dunmorogh",
   "searinggorge",
   "twilighthighlands",
   "wetlands"
  ]
 },
 {
  "id": "dunmorogh",
  "name": "Dun Morogh",
  "terrain": "mountains",
  "landmass": "eastern-kingdoms",
  "faction": "alliance",
  "landmark": "Ironforge",
  "mountain": true,
  "coastal": true,
  "polygon": [
   [
    636,
    466
   ],
   [
    656,
    428
   ],
   [
    648.63,
    414.01
   ],
   [
    717.66,
    424.79
   ],
   [
    726.79,
    446.26
   ],
   [
    702.17,
    488.64
   ],
   [
    640.78,
    493.49
   ]
  ],
  "center": [
   679.38,
   455.36
  ],
  "neighbors": [
   "elwynn",
   "lochmodan",
   "searinggorge",
   "wetlands"
  ]
 },
 {
  "id": "badlands",
  "name": "Badlands",
  "terrain": "wasteland",
  "landmass": "eastern-kingdoms",
  "lostTribe": true,
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    753.87,
    453.22
   ],
   [
    801.06,
    414.36
   ],
   [
    847.08,
    433.53
   ],
   [
    850,
    470
   ],
   [
    845.51,
    478.57
   ],
   [
    781.12,
    488.04
   ]
  ],
  "center": [
   806.19,
   453.94
  ],
  "neighbors": [
   "burningsteppes",
   "lochmodan",
   "searinggorge",
   "twilighthighlands"
  ]
 },
 {
  "id": "searinggorge",
  "name": "Searing Gorge",
  "terrain": "mountains",
  "landmass": "eastern-kingdoms",
  "mountain": true,
  "coastal": false,
  "polygon": [
   [
    702.17,
    488.64
   ],
   [
    726.79,
    446.26
   ],
   [
    753.87,
    453.22
   ],
   [
    781.12,
    488.04
   ],
   [
    761.68,
    522.05
   ],
   [
    729.83,
    527.36
   ]
  ],
  "center": [
   741.18,
   488.03
  ],
  "neighbors": [
   "badlands",
   "burningsteppes",
   "dunmorogh",
   "elwynn",
   "lochmodan",
   "redridge"
  ]
 },
 {
  "id": "burningsteppes",
  "name": "Burning Steppes",
  "terrain": "mountains",
  "landmass": "eastern-kingdoms",
  "landmark": "Blackrock Mountain",
  "mountain": true,
  "coastal": true,
  "polygon": [
   [
    761.68,
    522.05
   ],
   [
    781.12,
    488.04
   ],
   [
    845.51,
    478.57
   ],
   [
    828,
    512
   ],
   [
    840.46,
    551.17
   ],
   [
    796.55,
    560.41
   ]
  ],
  "center": [
   804.85,
   519.11
  ],
  "neighbors": [
   "badlands",
   "redridge",
   "searinggorge",
   "swampofsorrows"
  ]
 },
 {
  "id": "elwynn",
  "name": "Elwynn Forest",
  "terrain": "forest",
  "landmass": "eastern-kingdoms",
  "faction": "alliance",
  "landmark": "Stormwind",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    640.78,
    493.49
   ],
   [
    702.17,
    488.64
   ],
   [
    729.83,
    527.36
   ],
   [
    709.23,
    571.13
   ],
   [
    701.44,
    571.48
   ],
   [
    658.97,
    541.93
   ],
   [
    644,
    512
   ]
  ],
  "center": [
   686.93,
   524.84
  ],
  "neighbors": [
   "dunmorogh",
   "duskwood",
   "redridge",
   "searinggorge",
   "westfall"
  ]
 },
 {
  "id": "westfall",
  "name": "Westfall",
  "terrain": "fields",
  "landmass": "eastern-kingdoms",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    646,
    588
   ],
   [
    664,
    552
   ],
   [
    658.97,
    541.93
   ],
   [
    701.44,
    571.48
   ],
   [
    654.04,
    612.11
   ]
  ],
  "center": [
   669.41,
   577.79
  ],
  "neighbors": [
   "duskwood",
   "elwynn"
  ]
 },
 {
  "id": "redridge",
  "name": "Redridge Mountains",
  "terrain": "mountains",
  "landmass": "eastern-kingdoms",
  "mountain": true,
  "coastal": false,
  "polygon": [
   [
    709.23,
    571.13
   ],
   [
    729.83,
    527.36
   ],
   [
    761.68,
    522.05
   ],
   [
    796.55,
    560.41
   ],
   [
    785.04,
    579.6
   ],
   [
    723.66,
    587.61
   ]
  ],
  "center": [
   751.26,
   557.37
  ],
  "neighbors": [
   "burningsteppes",
   "deadwind",
   "duskwood",
   "elwynn",
   "searinggorge",
   "swampofsorrows"
  ]
 },
 {
  "id": "deadwind",
  "name": "Deadwind Pass",
  "terrain": "hills",
  "landmass": "eastern-kingdoms",
  "landmark": "Karazhan",
  "mountain": false,
  "coastal": false,
  "polygon": [
   [
    723.66,
    587.61
   ],
   [
    785.04,
    579.6
   ],
   [
    792.54,
    620.12
   ],
   [
    758.44,
    655.77
   ],
   [
    731.02,
    639.17
   ]
  ],
  "center": [
   757.69,
   613.54
  ],
  "neighbors": [
   "blastedlands",
   "duskwood",
   "nstranglethorn",
   "redridge",
   "swampofsorrows"
  ]
 },
 {
  "id": "duskwood",
  "name": "Duskwood",
  "terrain": "forest",
  "landmass": "eastern-kingdoms",
  "lostTribe": true,
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    654.04,
    612.11
   ],
   [
    701.44,
    571.48
   ],
   [
    709.23,
    571.13
   ],
   [
    723.66,
    587.61
   ],
   [
    731.02,
    639.17
   ],
   [
    678.33,
    658.33
   ],
   [
    660,
    630
   ]
  ],
  "center": [
   695.34,
   616.35
  ],
  "neighbors": [
   "deadwind",
   "elwynn",
   "nstranglethorn",
   "redridge",
   "westfall"
  ]
 },
 {
  "id": "swampofsorrows",
  "name": "Swamp of Sorrows",
  "terrain": "swamp",
  "landmass": "eastern-kingdoms",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    785.04,
    579.6
   ],
   [
    796.55,
    560.41
   ],
   [
    840.46,
    551.17
   ],
   [
    842,
    556
   ],
   [
    846,
    606
   ],
   [
    834.03,
    626.26
   ],
   [
    792.54,
    620.12
   ]
  ],
  "center": [
   817.28,
   589.49
  ],
  "neighbors": [
   "blastedlands",
   "burningsteppes",
   "deadwind",
   "redridge"
  ]
 },
 {
  "id": "blastedlands",
  "name": "Blasted Lands",
  "terrain": "wasteland",
  "landmass": "eastern-kingdoms",
  "landmark": "The Dark Portal",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    758.44,
    655.77
   ],
   [
    792.54,
    620.12
   ],
   [
    834.03,
    626.26
   ],
   [
    820,
    650
   ],
   [
    790,
    676
   ],
   [
    774.92,
    703.14
   ]
  ],
  "center": [
   791.62,
   652.26
  ],
  "neighbors": [
   "deadwind",
   "nstranglethorn",
   "swampofsorrows"
  ]
 },
 {
  "id": "nstranglethorn",
  "name": "Northern Stranglethorn",
  "terrain": "forest",
  "landmass": "eastern-kingdoms",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    664,
    700
   ],
   [
    682,
    664
   ],
   [
    678.33,
    658.33
   ],
   [
    731.02,
    639.17
   ],
   [
    758.44,
    655.77
   ],
   [
    774.92,
    703.14
   ],
   [
    770,
    712
   ],
   [
    769.16,
    713.09
   ],
   [
    665.63,
    705.42
   ]
  ],
  "center": [
   721.83,
   680.72
  ],
  "neighbors": [
   "blastedlands",
   "capestranglethorn",
   "deadwind",
   "duskwood"
  ]
 },
 {
  "id": "capestranglethorn",
  "name": "The Cape of Stranglethorn",
  "terrain": "swamp",
  "landmass": "eastern-kingdoms",
  "landmark": "Booty Bay",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    665.63,
    705.42
   ],
   [
    769.16,
    713.09
   ],
   [
    742,
    748
   ],
   [
    706,
    762
   ],
   [
    676,
    740
   ]
  ],
  "center": [
   713.21,
   729.56
  ],
  "neighbors": [
   "nstranglethorn"
  ]
 },
 {
  "id": "tolbarad",
  "name": "Tol Barad",
  "terrain": "fields",
  "landmass": "tolbarad",
  "landmark": "Baradin Hold",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    582,
    418
   ],
   [
    590,
    396
   ],
   [
    618,
    388
   ],
   [
    636,
    406
   ],
   [
    628,
    430
   ],
   [
    600,
    436
   ]
  ],
  "center": [
   609.25,
   412.35
  ],
  "neighbors": []
 },
 {
  "id": "kezan",
  "name": "Kezan",
  "terrain": "hills",
  "landmass": "kezan",
  "faction": "neutral",
  "landmark": "Undermine",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    444,
    766
   ],
   [
    452,
    736
   ],
   [
    486,
    728
   ],
   [
    508,
    748
   ],
   [
    500,
    776
   ],
   [
    468,
    786
   ]
  ],
  "center": [
   475.89,
   756.59
  ],
  "neighbors": []
 },
 {
  "id": "theramore",
  "name": "Theramore Isle",
  "terrain": "swamp",
  "landmass": "theramore",
  "faction": "alliance",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    364,
    492
   ],
   [
    372,
    470
   ],
   [
    400,
    462
   ],
   [
    418,
    482
   ],
   [
    408,
    506
   ],
   [
    380,
    510
   ]
  ],
  "center": [
   390.94,
   486.77
  ],
  "neighbors": []
 },
 {
  "id": "maelstrom",
  "name": "The Maelstrom",
  "terrain": "wasteland",
  "landmass": "maelstrom",
  "landmark": "Deepholm",
  "lostTribe": true,
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    476,
    444
   ],
   [
    486,
    424
   ],
   [
    518,
    414
   ],
   [
    546,
    434
   ],
   [
    546,
    466
   ],
   [
    516,
    484
   ],
   [
    486,
    468
   ]
  ],
  "center": [
   512.94,
   448.21
  ],
  "neighbors": []
 }
]
