// AUTO-GENERATED by scripts/genOfficialMap.ts — mapa oficial S/M/L exacto
// 6 islas: 2 small (7), 2 medium (9), 2 large (11) = 54 regiones
import type { RegionData } from './types'

export const REGIONS: RegionData[] = [
 {
  "id": "sa1",
  "name": "Cima del Vigía",
  "terrain": "mountains",
  "landmass": "small_a",
  "faction": "neutral",
  "mountain": true,
  "coastal": true,
  "polygon": [
   [
    137,
    96.42
   ],
   [
    156.44,
    75.84
   ],
   [
    198.74,
    30.68
   ],
   [
    245.42,
    45.81
   ],
   [
    266.77,
    58.07
   ],
   [
    229.57,
    151.09
   ],
   [
    168.71,
    141.72
   ]
  ],
  "center": [
   204.09,
   91.98
  ],
  "neighbors": [
   "sa2",
   "sa3",
   "sa4"
  ]
 },
 {
  "id": "sa2",
  "name": "Campos de Westfall",
  "terrain": "fields",
  "landmass": "small_a",
  "faction": "alliance",
  "landmark": "S",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    229.57,
    151.09
   ],
   [
    266.77,
    58.07
   ],
   [
    288.62,
    70.61
   ],
   [
    320.9,
    100.54
   ],
   [
    347.09,
    150.18
   ],
   [
    357.86,
    183.16
   ],
   [
    263.71,
    196.61
   ]
  ],
  "center": [
   289.61,
   138.32
  ],
  "neighbors": [
   "sa1",
   "sa4",
   "sa5"
  ]
 },
 {
  "id": "sa3",
  "name": "Colinas de Hillsbrad",
  "terrain": "hills",
  "landmass": "small_a",
  "faction": "neutral",
  "lostTribe": true,
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    60.26,
    126.92
   ],
   [
    121.13,
    113.22
   ],
   [
    137,
    96.42
   ],
   [
    168.71,
    141.72
   ],
   [
    106.25,
    225
   ],
   [
    77.99,
    225
   ],
   [
    77.97,
    196.46
   ]
  ],
  "center": [
   110.87,
   159.47
  ],
  "neighbors": [
   "sa1",
   "sa4",
   "sa6"
  ]
 },
 {
  "id": "sa4",
  "name": "Bosque de Elwynn",
  "terrain": "forest",
  "landmass": "small_a",
  "faction": "alliance",
  "mountain": false,
  "coastal": false,
  "polygon": [
   [
    106.25,
    225
   ],
   [
    168.71,
    141.72
   ],
   [
    229.57,
    151.09
   ],
   [
    263.71,
    196.61
   ],
   [
    236.29,
    273.39
   ],
   [
    171.15,
    282.69
   ]
  ],
  "center": [
   190.39,
   213.32
  ],
  "neighbors": [
   "sa1",
   "sa2",
   "sa3",
   "sa5",
   "sa6",
   "sa7"
  ]
 },
 {
  "id": "sa5",
  "name": "Montañas Crestagrana",
  "terrain": "mountains",
  "landmass": "small_a",
  "faction": "alliance",
  "mountain": true,
  "coastal": true,
  "polygon": [
   [
    236.29,
    273.39
   ],
   [
    263.71,
    196.61
   ],
   [
    357.86,
    183.16
   ],
   [
    368.41,
    215.47
   ],
   [
    365.41,
    279.46
   ],
   [
    316.23,
    326.11
   ],
   [
    289.74,
    344.65
   ]
  ],
  "center": [
   306.2,
   255.49
  ],
  "neighbors": [
   "sa2",
   "sa4",
   "sa7"
  ]
 },
 {
  "id": "sa6",
  "name": "Llanos de Mulgore",
  "terrain": "fields",
  "landmass": "small_a",
  "faction": "horde",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    72.68,
    323.8
   ],
   [
    78.02,
    257.08
   ],
   [
    77.99,
    225
   ],
   [
    106.25,
    225
   ],
   [
    171.15,
    282.69
   ],
   [
    134.49,
    356.03
   ],
   [
    114.86,
    344.52
   ]
  ],
  "center": [
   115.18,
   288.75
  ],
  "neighbors": [
   "sa3",
   "sa4",
   "sa7"
  ]
 },
 {
  "id": "sa7",
  "name": "Pantano de los Zánganos",
  "terrain": "swamp",
  "landmass": "small_a",
  "faction": "neutral",
  "lostTribe": true,
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    134.49,
    356.03
   ],
   [
    171.15,
    282.69
   ],
   [
    236.29,
    273.39
   ],
   [
    289.74,
    344.65
   ],
   [
    257.02,
    367.55
   ],
   [
    198.53,
    411.68
   ],
   [
    156,
    368.64
   ]
  ],
  "center": [
   209.21,
   337.26
  ],
  "neighbors": [
   "sa4",
   "sa5",
   "sa6"
  ]
 },
 {
  "id": "sb1",
  "name": "Montañas de Alterac",
  "terrain": "mountains",
  "landmass": "small_b",
  "mountain": true,
  "coastal": true,
  "polygon": [
   [
    501.59,
    105.37
   ],
   [
    515.63,
    80.09
   ],
   [
    537.25,
    43.16
   ],
   [
    601.62,
    54.31
   ],
   [
    632.07,
    73.49
   ],
   [
    619.25,
    121.56
   ],
   [
    564.2,
    144.5
   ]
  ],
  "center": [
   568.83,
   92.26
  ],
  "neighbors": [
   "sb2",
   "sb3",
   "sb4"
  ]
 },
 {
  "id": "sb2",
  "name": "Campos de Arathi",
  "terrain": "fields",
  "landmass": "small_b",
  "landmark": "S",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    619.25,
    121.56
   ],
   [
    632.07,
    73.49
   ],
   [
    658.68,
    90.25
   ],
   [
    737.43,
    87.92
   ],
   [
    763.05,
    145.11
   ],
   [
    749.47,
    184.36
   ],
   [
    677.69,
    194.62
   ]
  ],
  "center": [
   693.44,
   135.29
  ],
  "neighbors": [
   "sb1",
   "sb4",
   "sb5"
  ]
 },
 {
  "id": "sb3",
  "name": "Bosque de Argénteos",
  "terrain": "forest",
  "landmass": "small_b",
  "faction": "alliance",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    462.85,
    140.45
   ],
   [
    496,
    115.45
   ],
   [
    501.59,
    105.37
   ],
   [
    564.2,
    144.5
   ],
   [
    530,
    230
   ],
   [
    482.83,
    230
   ],
   [
    480.14,
    203.97
   ]
  ],
  "center": [
   510.95,
   169.84
  ],
  "neighbors": [
   "sb1",
   "sb4",
   "sb6"
  ]
 },
 {
  "id": "sb4",
  "name": "Claro de Tirisfal",
  "terrain": "forest",
  "landmass": "small_b",
  "lostTribe": true,
  "mountain": false,
  "coastal": false,
  "polygon": [
   [
    530,
    230
   ],
   [
    564.2,
    144.5
   ],
   [
    619.25,
    121.56
   ],
   [
    677.69,
    194.62
   ],
   [
    640,
    270
   ],
   [
    570,
    270
   ]
  ],
  "center": [
   603.47,
   203.44
  ],
  "neighbors": [
   "sb1",
   "sb2",
   "sb3",
   "sb5",
   "sb6",
   "sb7"
  ]
 },
 {
  "id": "sb5",
  "name": "Montañas de Colmillo",
  "terrain": "mountains",
  "landmass": "small_b",
  "mountain": true,
  "coastal": true,
  "polygon": [
   [
    640,
    270
   ],
   [
    677.69,
    194.62
   ],
   [
    749.47,
    184.36
   ],
   [
    739.11,
    214.31
   ],
   [
    777.73,
    283.09
   ],
   [
    717.02,
    320.57
   ],
   [
    676.74,
    325.11
   ]
  ],
  "center": [
   706.23,
   257.9
  ],
  "neighbors": [
   "sb2",
   "sb4",
   "sb7"
  ]
 },
 {
  "id": "sb6",
  "name": "Praderas de Loch Modan",
  "terrain": "fields",
  "landmass": "small_b",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    461.82,
    336.17
   ],
   [
    485.71,
    257.91
   ],
   [
    482.83,
    230
   ],
   [
    530,
    230
   ],
   [
    570,
    270
   ],
   [
    535.81,
    355.48
   ],
   [
    501.63,
    366.56
   ]
  ],
  "center": [
   514.28,
   296.03
  ],
  "neighbors": [
   "sb3",
   "sb4",
   "sb7"
  ]
 },
 {
  "id": "sb7",
  "name": "Ciénaga de Dustwallow",
  "terrain": "swamp",
  "landmass": "small_b",
  "lostTribe": true,
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    535.81,
    355.48
   ],
   [
    570,
    270
   ],
   [
    640,
    270
   ],
   [
    676.74,
    325.11
   ],
   [
    646.29,
    328.55
   ],
   [
    601.14,
    369.59
   ],
   [
    561.76,
    347.06
   ]
  ],
  "center": [
   603.05,
   314.39
  ],
  "neighbors": [
   "sb4",
   "sb5",
   "sb6"
  ]
 },
 {
  "id": "ma1",
  "name": "Pantano de las Penas",
  "terrain": "swamp",
  "landmass": "medium_a",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    78.99,
    499
   ],
   [
    80.41,
    488.61
   ],
   [
    110.87,
    469.32
   ],
   [
    122.36,
    427.8
   ],
   [
    191.15,
    434.45
   ],
   [
    230.67,
    447.45
   ],
   [
    216.9,
    550.71
   ]
  ],
  "center": [
   166.11,
   483.66
  ],
  "neighbors": [
   "ma2",
   "ma8"
  ]
 },
 {
  "id": "ma2",
  "name": "Campos de Trabalomas",
  "terrain": "fields",
  "landmass": "medium_a",
  "landmark": "M",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    216.9,
    550.71
   ],
   [
    230.67,
    447.45
   ],
   [
    257.69,
    456.33
   ],
   [
    320.47,
    464.68
   ],
   [
    354.81,
    485.6
   ],
   [
    377.17,
    507.4
   ],
   [
    269,
    575
   ],
   [
    242,
    575
   ],
   [
    220.53,
    561.58
   ]
  ],
  "center": [
   281.52,
   511.33
  ],
  "neighbors": [
   "ma1",
   "ma3",
   "ma4",
   "ma8",
   "ma9"
  ]
 },
 {
  "id": "ma3",
  "name": "Bosque de Terokkar",
  "terrain": "forest",
  "landmass": "medium_a",
  "faction": "neutral",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    269,
    575
   ],
   [
    377.17,
    507.4
   ],
   [
    387.47,
    517.44
   ],
   [
    410.17,
    557.61
   ],
   [
    398.14,
    649.15
   ],
   [
    397.22,
    666.59
   ]
  ],
  "center": [
   356.59,
   581.24
  ],
  "neighbors": [
   "ma2",
   "ma4"
  ]
 },
 {
  "id": "ma4",
  "name": "Caverna de Desolace",
  "terrain": "swamp",
  "landmass": "medium_a",
  "lostTribe": true,
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    242,
    575
   ],
   [
    269,
    575
   ],
   [
    397.22,
    666.59
   ],
   [
    396.11,
    687.65
   ],
   [
    275,
    734.23
   ],
   [
    256.5,
    720
   ]
  ],
  "center": [
   304.99,
   658.84
  ],
  "neighbors": [
   "ma2",
   "ma3",
   "ma5",
   "ma6",
   "ma9"
  ]
 },
 {
  "id": "ma5",
  "name": "Montañas de Cumbre Borrascosa",
  "terrain": "mountains",
  "landmass": "medium_a",
  "mountain": true,
  "coastal": true,
  "polygon": [
   [
    275,
    734.23
   ],
   [
    396.11,
    687.65
   ],
   [
    393.43,
    738.55
   ],
   [
    381.9,
    820.06
   ],
   [
    321.18,
    829.5
   ],
   [
    275,
    832.27
   ]
  ],
  "center": [
   335.33,
   767.21
  ],
  "neighbors": [
   "ma4",
   "ma6"
  ]
 },
 {
  "id": "ma6",
  "name": "Colinas de Feralas",
  "terrain": "hills",
  "landmass": "medium_a",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    123.73,
    776.27
   ],
   [
    180,
    720
   ],
   [
    256.5,
    720
   ],
   [
    275,
    734.23
   ],
   [
    275,
    832.27
   ],
   [
    255.71,
    833.43
   ],
   [
    187.83,
    849.15
   ],
   [
    161.71,
    777.55
   ]
  ],
  "center": [
   216.27,
   778.17
  ],
  "neighbors": [
   "ma4",
   "ma5",
   "ma7",
   "ma9"
  ]
 },
 {
  "id": "ma7",
  "name": "Bosque de Frondavil",
  "terrain": "forest",
  "landmass": "medium_a",
  "faction": "alliance",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    77.36,
    729.56
   ],
   [
    91.43,
    660.3
   ],
   [
    88.23,
    630
   ],
   [
    135,
    630
   ],
   [
    180,
    720
   ],
   [
    123.73,
    776.27
   ],
   [
    105.42,
    775.66
   ]
  ],
  "center": [
   122.86,
   702.52
  ],
  "neighbors": [
   "ma6",
   "ma8",
   "ma9"
  ]
 },
 {
  "id": "ma8",
  "name": "Praderas de Vallefresno",
  "terrain": "hills",
  "landmass": "medium_a",
  "lostTribe": true,
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    74.47,
    532.07
   ],
   [
    78.99,
    499
   ],
   [
    216.9,
    550.71
   ],
   [
    220.53,
    561.58
   ],
   [
    135,
    630
   ],
   [
    88.23,
    630
   ],
   [
    85.07,
    600.05
   ]
  ],
  "center": [
   132.56,
   567.56
  ],
  "neighbors": [
   "ma1",
   "ma2",
   "ma7",
   "ma9"
  ]
 },
 {
  "id": "ma9",
  "name": "Campos de Costasur",
  "terrain": "fields",
  "landmass": "medium_a",
  "mountain": false,
  "coastal": false,
  "polygon": [
   [
    135,
    630
   ],
   [
    220.53,
    561.58
   ],
   [
    242,
    575
   ],
   [
    256.5,
    720
   ],
   [
    180,
    720
   ]
  ],
  "center": [
   204.44,
   649.2
  ],
  "neighbors": [
   "ma2",
   "ma4",
   "ma6",
   "ma7",
   "ma8"
  ]
 },
 {
  "id": "mb1",
  "name": "Bosque de Ashenvale",
  "terrain": "forest",
  "landmass": "medium_b",
  "faction": "alliance",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    494.76,
    564.84
   ],
   [
    525.1,
    456.59
   ],
   [
    542.59,
    427.2
   ],
   [
    593.43,
    435.23
   ],
   [
    600,
    433.22
   ],
   [
    600,
    517.5
   ],
   [
    495.23,
    569.88
   ]
  ],
  "center": [
   552.88,
   492.6
  ],
  "neighbors": [
   "mb2",
   "mb5"
  ]
 },
 {
  "id": "mb2",
  "name": "Ciénaga de Marjal Revolcafango",
  "terrain": "swamp",
  "landmass": "medium_b",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    600,
    433.22
   ],
   [
    631.95,
    423.44
   ],
   [
    701.35,
    441.76
   ],
   [
    731.84,
    438.72
   ],
   [
    713.75,
    574.38
   ],
   [
    600,
    517.5
   ]
  ],
  "center": [
   665.37,
   489.7
  ],
  "neighbors": [
   "mb1",
   "mb3",
   "mb5"
  ]
 },
 {
  "id": "mb3",
  "name": "Campos de Vega de Tuercespina",
  "terrain": "fields",
  "landmass": "medium_b",
  "landmark": "M",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    713.75,
    574.38
   ],
   [
    731.84,
    438.72
   ],
   [
    776.54,
    434.27
   ],
   [
    839.75,
    457.6
   ],
   [
    848.44,
    503.98
   ],
   [
    856.36,
    520.4
   ],
   [
    745,
    590
   ],
   [
    720,
    590
   ]
  ],
  "center": [
   776.4,
   507.49
  ],
  "neighbors": [
   "mb2",
   "mb4",
   "mb5",
   "mb7"
  ]
 },
 {
  "id": "mb4",
  "name": "Montañas de Filospada",
  "terrain": "mountains",
  "landmass": "medium_b",
  "mountain": true,
  "coastal": true,
  "polygon": [
   [
    745,
    590
   ],
   [
    856.36,
    520.4
   ],
   [
    865.45,
    539.23
   ],
   [
    903.49,
    568.33
   ],
   [
    880.75,
    614.89
   ],
   [
    861.2,
    648.1
   ]
  ],
  "center": [
   835.35,
   585.25
  ],
  "neighbors": [
   "mb3",
   "mb7"
  ]
 },
 {
  "id": "mb5",
  "name": "Colinas de Desolace",
  "terrain": "hills",
  "landmass": "medium_b",
  "lostTribe": true,
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    495.23,
    569.88
   ],
   [
    600,
    517.5
   ],
   [
    713.75,
    574.38
   ],
   [
    720,
    590
   ],
   [
    707.5,
    615
   ],
   [
    499.43,
    615
   ]
  ],
  "center": [
   603.77,
   577.98
  ],
  "neighbors": [
   "mb1",
   "mb2",
   "mb3",
   "mb6",
   "mb7"
  ]
 },
 {
  "id": "mb6",
  "name": "Bosque de Vega Crepuscular",
  "terrain": "forest",
  "landmass": "medium_b",
  "lostTribe": true,
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    499.43,
    615
   ],
   [
    707.5,
    615
   ],
   [
    694.47,
    701.84
   ],
   [
    612.14,
    729.29
   ],
   [
    506.29,
    688.57
   ]
  ],
  "center": [
   604.73,
   663.09
  ],
  "neighbors": [
   "mb5",
   "mb7",
   "mb8",
   "mb9"
  ]
 },
 {
  "id": "mb7",
  "name": "Campos de los Baldíos Sur",
  "terrain": "fields",
  "landmass": "medium_b",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    694.47,
    701.84
   ],
   [
    707.5,
    615
   ],
   [
    720,
    590
   ],
   [
    745,
    590
   ],
   [
    861.2,
    648.1
   ],
   [
    854.95,
    658.72
   ],
   [
    844.66,
    707.39
   ],
   [
    781.11,
    765.01
   ],
   [
    749.92,
    771.15
   ]
  ],
  "center": [
   769.43,
   677.72
  ],
  "neighbors": [
   "mb3",
   "mb4",
   "mb5",
   "mb6",
   "mb9"
  ]
 },
 {
  "id": "mb8",
  "name": "Montañas de Sierra Espolón",
  "terrain": "mountains",
  "landmass": "medium_b",
  "mountain": true,
  "coastal": true,
  "polygon": [
   [
    506.29,
    688.57
   ],
   [
    612.14,
    729.29
   ],
   [
    593.7,
    821.52
   ],
   [
    563.76,
    818.71
   ],
   [
    513.02,
    822.9
   ],
   [
    507.16,
    697.91
   ]
  ],
  "center": [
   554.01,
   761.62
  ],
  "neighbors": [
   "mb6",
   "mb9"
  ]
 },
 {
  "id": "mb9",
  "name": "Bosque de Claro de la Luna",
  "terrain": "forest",
  "landmass": "medium_b",
  "faction": "neutral",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    593.7,
    821.52
   ],
   [
    612.14,
    729.29
   ],
   [
    694.47,
    701.84
   ],
   [
    749.92,
    771.15
   ],
   [
    705.01,
    779.98
   ],
   [
    641.89,
    835.13
   ],
   [
    604.95,
    822.58
   ]
  ],
  "center": [
   660.6,
   766.49
  ],
  "neighbors": [
   "mb6",
   "mb7",
   "mb8"
  ]
 },
 {
  "id": "la1",
  "name": "Pantano de Zangarmar",
  "terrain": "swamp",
  "landmass": "large_a",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    106.58,
    914.3
   ],
   [
    115.55,
    914.4
   ],
   [
    131.59,
    897.37
   ],
   [
    203.19,
    918.48
   ],
   [
    239.94,
    916.99
   ],
   [
    223.17,
    1012.04
   ],
   [
    155,
    995
   ]
  ],
  "center": [
   179.53,
   951.59
  ],
  "neighbors": [
   "la10",
   "la2",
   "la9"
  ]
 },
 {
  "id": "la2",
  "name": "Campos de Elwynn",
  "terrain": "fields",
  "landmass": "large_a",
  "landmark": "L",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    223.17,
    1012.04
   ],
   [
    239.94,
    916.99
   ],
   [
    268.83,
    915.82
   ],
   [
    353.08,
    892.67
   ],
   [
    378.95,
    952.14
   ],
   [
    400.16,
    969.3
   ],
   [
    328.85,
    1032.69
   ],
   [
    225.84,
    1017.98
   ]
  ],
  "center": [
   305.12,
   966.46
  ],
  "neighbors": [
   "la1",
   "la3",
   "la4",
   "la9"
  ]
 },
 {
  "id": "la3",
  "name": "Montañas de Dun Morogh",
  "terrain": "mountains",
  "landmass": "large_a",
  "mountain": true,
  "coastal": true,
  "polygon": [
   [
    328.85,
    1032.69
   ],
   [
    400.16,
    969.3
   ],
   [
    421.91,
    986.9
   ],
   [
    463.09,
    1027.06
   ],
   [
    425.02,
    1091.02
   ],
   [
    442.17,
    1115
   ],
   [
    370,
    1115
   ]
  ],
  "center": [
   396.3,
   1047.02
  ],
  "neighbors": [
   "la2",
   "la4",
   "la5"
  ]
 },
 {
  "id": "la4",
  "name": "Colinas de Loch Modan",
  "terrain": "hills",
  "landmass": "large_a",
  "faction": "alliance",
  "mountain": false,
  "coastal": false,
  "polygon": [
   [
    223.46,
    1026.54
   ],
   [
    225.84,
    1017.98
   ],
   [
    328.85,
    1032.69
   ],
   [
    370,
    1115
   ],
   [
    296.25,
    1207.19
   ],
   [
    278.95,
    1211.51
   ]
  ],
  "center": [
   295.14,
   1102.16
  ],
  "neighbors": [
   "la11",
   "la2",
   "la3",
   "la5",
   "la6",
   "la9"
  ]
 },
 {
  "id": "la5",
  "name": "Campos de Westfall",
  "terrain": "fields",
  "landmass": "large_a",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    296.25,
    1207.19
   ],
   [
    370,
    1115
   ],
   [
    442.17,
    1115
   ],
   [
    467.41,
    1150.3
   ],
   [
    467.41,
    1213.42
   ],
   [
    406.64,
    1237.57
   ],
   [
    406.37,
    1253.07
   ]
  ],
  "center": [
   394.44,
   1179.46
  ],
  "neighbors": [
   "la3",
   "la4",
   "la6"
  ]
 },
 {
  "id": "la6",
  "name": "Montañas de Crestagrana",
  "terrain": "mountains",
  "landmass": "large_a",
  "mountain": true,
  "coastal": true,
  "polygon": [
   [
    243.57,
    1354.27
   ],
   [
    255.81,
    1231.94
   ],
   [
    278.95,
    1211.51
   ],
   [
    296.25,
    1207.19
   ],
   [
    406.37,
    1253.07
   ],
   [
    405.43,
    1307.87
   ],
   [
    383.29,
    1364.11
   ],
   [
    294.19,
    1358.14
   ]
  ],
  "center": [
   323.06,
   1291.86
  ],
  "neighbors": [
   "la11",
   "la4",
   "la5",
   "la7"
  ]
 },
 {
  "id": "la7",
  "name": "Bosque de Tuercespina",
  "terrain": "forest",
  "landmass": "large_a",
  "lostTribe": true,
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    100.68,
    1294.95
   ],
   [
    109.48,
    1237.66
   ],
   [
    195.53,
    1211.84
   ],
   [
    255.81,
    1231.94
   ],
   [
    243.57,
    1354.27
   ],
   [
    204.18,
    1351.26
   ],
   [
    136.57,
    1303.81
   ]
  ],
  "center": [
   187.29,
   1277.65
  ],
  "neighbors": [
   "la11",
   "la6",
   "la8"
  ]
 },
 {
  "id": "la8",
  "name": "Montañas de Vega de Tuercespina",
  "terrain": "mountains",
  "landmass": "large_a",
  "mountain": true,
  "coastal": true,
  "polygon": [
   [
    80.33,
    1203.11
   ],
   [
    84.86,
    1115
   ],
   [
    135,
    1115
   ],
   [
    195.53,
    1211.84
   ],
   [
    109.48,
    1237.66
   ],
   [
    110.88,
    1228.54
   ]
  ],
  "center": [
   127.03,
   1176.39
  ],
  "neighbors": [
   "la11",
   "la7",
   "la9"
  ]
 },
 {
  "id": "la9",
  "name": "Praderas de Mulgore",
  "terrain": "hills",
  "landmass": "large_a",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    62.14,
    1015.64
   ],
   [
    155,
    995
   ],
   [
    223.17,
    1012.04
   ],
   [
    225.84,
    1017.98
   ],
   [
    223.46,
    1026.54
   ],
   [
    135,
    1115
   ],
   [
    84.86,
    1115
   ],
   [
    85.04,
    1111.46
   ]
  ],
  "center": [
   135,
   1049.59
  ],
  "neighbors": [
   "la1",
   "la10",
   "la11",
   "la2",
   "la4",
   "la8"
  ]
 },
 {
  "id": "la10",
  "name": "Bosque de Claros de Tirisfal",
  "terrain": "forest",
  "landmass": "large_a",
  "faction": "horde",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    50.09,
    911.35
   ],
   [
    86.19,
    914.07
   ],
   [
    106.58,
    914.3
   ],
   [
    155,
    995
   ],
   [
    62.14,
    1015.64
   ],
   [
    62.13,
    1015.59
   ]
  ],
  "center": [
   93.68,
   963.77
  ],
  "neighbors": [
   "la1",
   "la9"
  ]
 },
 {
  "id": "la11",
  "name": "Ciénaga de las Mil Agujas",
  "terrain": "swamp",
  "landmass": "large_a",
  "lostTribe": true,
  "mountain": false,
  "coastal": false,
  "polygon": [
   [
    135,
    1115
   ],
   [
    223.46,
    1026.54
   ],
   [
    278.95,
    1211.51
   ],
   [
    255.81,
    1231.94
   ],
   [
    195.53,
    1211.84
   ]
  ],
  "center": [
   211.73,
   1139.29
  ],
  "neighbors": [
   "la4",
   "la6",
   "la7",
   "la8",
   "la9"
  ]
 },
 {
  "id": "lb1",
  "name": "Bosque de Cuna del Invierno",
  "terrain": "forest",
  "landmass": "large_b",
  "faction": "neutral",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    560.33,
    883.43
   ],
   [
    598.76,
    874.88
   ],
   [
    649.48,
    889.37
   ],
   [
    650,
    889.01
   ],
   [
    650,
    990
   ],
   [
    592.14,
    1038.21
   ],
   [
    576.75,
    1042.06
   ],
   [
    571.59,
    1000.69
   ]
  ],
  "center": [
   605.6,
   949.36
  ],
  "neighbors": [
   "lb2",
   "lb5",
   "lb6"
  ]
 },
 {
  "id": "lb2",
  "name": "Pantano de Feralas",
  "terrain": "swamp",
  "landmass": "large_b",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    650,
    889.01
   ],
   [
    683.43,
    866.08
   ],
   [
    751.5,
    901.34
   ],
   [
    782.18,
    909.08
   ],
   [
    766,
    990
   ],
   [
    650,
    990
   ]
  ],
  "center": [
   708.71,
   936.46
  ],
  "neighbors": [
   "lb1",
   "lb3",
   "lb5"
  ]
 },
 {
  "id": "lb3",
  "name": "Campos de Tanaris",
  "terrain": "fields",
  "landmass": "large_b",
  "landmark": "L",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    766,
    990
   ],
   [
    782.18,
    909.08
   ],
   [
    812.55,
    916.75
   ],
   [
    886.32,
    912.57
   ],
   [
    895.7,
    964.88
   ],
   [
    916.88,
    981.74
   ],
   [
    800,
    1046.67
   ]
  ],
  "center": [
   831.53,
   970.2
  ],
  "neighbors": [
   "lb2",
   "lb4",
   "lb5"
  ]
 },
 {
  "id": "lb4",
  "name": "Montañas de Cuna del Invierno",
  "terrain": "mountains",
  "landmass": "large_b",
  "mountain": true,
  "coastal": true,
  "polygon": [
   [
    800,
    1046.67
   ],
   [
    916.88,
    981.74
   ],
   [
    931.49,
    993.37
   ],
   [
    953.34,
    1033.36
   ],
   [
    945.14,
    1093.12
   ],
   [
    920.81,
    1132.62
   ],
   [
    803.09,
    1087.34
   ],
   [
    800,
    1075
   ]
  ],
  "center": [
   885.16,
   1059.18
  ],
  "neighbors": [
   "lb10",
   "lb3",
   "lb5",
   "lb7"
  ]
 },
 {
  "id": "lb5",
  "name": "Colinas de Silithus",
  "terrain": "hills",
  "landmass": "large_b",
  "lostTribe": true,
  "mountain": false,
  "coastal": false,
  "polygon": [
   [
    592.14,
    1038.21
   ],
   [
    650,
    990
   ],
   [
    766,
    990
   ],
   [
    800,
    1046.67
   ],
   [
    800,
    1075
   ],
   [
    651,
    1075
   ]
  ],
  "center": [
   704.51,
   1034.39
  ],
  "neighbors": [
   "lb1",
   "lb10",
   "lb2",
   "lb3",
   "lb4",
   "lb6"
  ]
 },
 {
  "id": "lb6",
  "name": "Bosque de Frondavil",
  "terrain": "forest",
  "landmass": "large_b",
  "lostTribe": true,
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    576.75,
    1042.06
   ],
   [
    592.14,
    1038.21
   ],
   [
    651,
    1075
   ],
   [
    723,
    1195
   ],
   [
    665,
    1195
   ],
   [
    581.72,
    1111.72
   ],
   [
    584,
    1100.29
   ]
  ],
  "center": [
   640.58,
   1121.96
  ],
  "neighbors": [
   "lb1",
   "lb10",
   "lb5",
   "lb8",
   "lb9"
  ]
 },
 {
  "id": "lb7",
  "name": "Campos de Vega de Tuercespina Sur",
  "terrain": "fields",
  "landmass": "large_b",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    742.43,
    1201.07
   ],
   [
    803.09,
    1087.34
   ],
   [
    920.81,
    1132.62
   ],
   [
    908.89,
    1151.96
   ],
   [
    909.45,
    1225.46
   ],
   [
    868.59,
    1258.16
   ],
   [
    744.6,
    1206.5
   ]
  ],
  "center": [
   837.21,
   1174.87
  ],
  "neighbors": [
   "lb10",
   "lb11",
   "lb4",
   "lb9"
  ]
 },
 {
  "id": "lb8",
  "name": "Montañas de Silithus",
  "terrain": "mountains",
  "landmass": "large_b",
  "mountain": true,
  "coastal": true,
  "polygon": [
   [
    564.09,
    1200.3
   ],
   [
    581.72,
    1111.72
   ],
   [
    665,
    1195
   ],
   [
    593.69,
    1239.57
   ],
   [
    588.73,
    1229.47
   ]
  ],
  "center": [
   605.06,
   1182.22
  ],
  "neighbors": [
   "lb6",
   "lb9"
  ]
 },
 {
  "id": "lb9",
  "name": "Bosque de Claro de la Luna Sur",
  "terrain": "forest",
  "landmass": "large_b",
  "mountain": false,
  "coastal": true,
  "polygon": [
   [
    593.69,
    1239.57
   ],
   [
    665,
    1195
   ],
   [
    723,
    1195
   ],
   [
    742.43,
    1201.07
   ],
   [
    744.6,
    1206.5
   ],
   [
    715,
    1317.51
   ],
   [
    692.7,
    1298.61
   ],
   [
    619.17,
    1313.03
   ],
   [
    606.3,
    1265.2
   ]
  ],
  "center": [
   672.69,
   1251.67
  ],
  "neighbors": [
   "lb10",
   "lb11",
   "lb6",
   "lb7",
   "lb8"
  ]
 },
 {
  "id": "lb10",
  "name": "Pantano de Dustwallow",
  "terrain": "swamp",
  "landmass": "large_b",
  "lostTribe": true,
  "mountain": false,
  "coastal": false,
  "polygon": [
   [
    651,
    1075
   ],
   [
    800,
    1075
   ],
   [
    803.09,
    1087.34
   ],
   [
    742.43,
    1201.07
   ],
   [
    723,
    1195
   ]
  ],
  "center": [
   731.47,
   1120.71
  ],
  "neighbors": [
   "lb4",
   "lb5",
   "lb6",
   "lb7",
   "lb9"
  ]
 },
 {
  "id": "lb11",
  "name": "Montañas de Tanaris",
  "terrain": "mountains",
  "landmass": "large_b",
  "mountain": true,
  "coastal": true,
  "polygon": [
   [
    715,
    1317.51
   ],
   [
    744.6,
    1206.5
   ],
   [
    868.59,
    1258.16
   ],
   [
    866.89,
    1259.52
   ],
   [
    844.97,
    1315.04
   ],
   [
    813.76,
    1349.23
   ],
   [
    751,
    1348.03
   ]
  ],
  "center": [
   785.65,
   1285.03
  ],
  "neighbors": [
   "lb7",
   "lb9"
  ]
 }
]
