/**
 * Builds the playable board from hand-placed region seeds:
 *  - Voronoi tessellation per landmass, clipped to the coastline outline
 *  - adjacency derived from shared polygon edges
 *  - coastal ("anchor") flag for regions touching the sea
 * Output: src/game/mapData.generated.ts
 */
import { Delaunay } from 'd3-delaunay'
import polygonClipping from 'polygon-clipping'
import { writeFileSync } from 'node:fs'
import { LANDMASSES } from './mapSeeds'
import type { SeedDef } from './mapSeeds'

type Pt = [number, number]
const Q = (n: number) => Math.round(n * 100) / 100
const key = (p: Pt) => `${Q(p[0])}:${Q(p[1])}`

function pointInPolygon(p: Pt, poly: Pt[]) {
  let inside = false
  for (let i = 0, j = poly.length - 1; i < poly.length; j = i++) {
    const [xi, yi] = poly[i]
    const [xj, yj] = poly[j]
    if (yi > p[1] !== yj > p[1] && p[0] < ((xj - xi) * (p[1] - yi)) / (yj - yi) + xi) inside = !inside
  }
  return inside
}

function centroid(poly: Pt[]): Pt {
  let a = 0, cx = 0, cy = 0
  for (let i = 0, j = poly.length - 1; i < poly.length; j = i++) {
    const f = poly[j][0] * poly[i][1] - poly[i][0] * poly[j][1]
    a += f
    cx += (poly[j][0] + poly[i][0]) * f
    cy += (poly[j][1] + poly[i][1]) * f
  }
  a *= 0.5
  if (Math.abs(a) < 1e-9) {
    const n = poly.length
    return [poly.reduce((s, p) => s + p[0], 0) / n, poly.reduce((s, p) => s + p[1], 0) / n]
  }
  return [cx / (6 * a), cy / (6 * a)]
}

function area(poly: Pt[]) {
  let a = 0
  for (let i = 0, j = poly.length - 1; i < poly.length; j = i++) {
    a += poly[j][0] * poly[i][1] - poly[i][0] * poly[j][1]
  }
  return Math.abs(a / 2)
}

interface OutRegion {
  id: string
  name: string
  terrain: string
  landmass: string
  faction?: string
  landmark?: string
  lostTribe?: boolean
  mountain: boolean
  coastal: boolean
  polygon: Pt[]
  center: Pt
  neighbors: string[]
}

const regions: OutRegion[] = []
const edgeOwners = new Map<string, string[]>()
const coastKeys = new Set<string>()
const problems: string[] = []

for (const land of LANDMASSES) {
  const outline = land.outline.map((p) => [Q(p[0]), Q(p[1])] as Pt)
  for (const s of land.seeds) {
    if (!pointInPolygon([s.x, s.y], outline)) problems.push(`seed OUTSIDE outline: ${land.id}/${s.id}`)
  }

  const xs = outline.map((p) => p[0])
  const ys = outline.map((p) => p[1])
  const bbox: [number, number, number, number] = [
    Math.min(...xs) - 40, Math.min(...ys) - 40, Math.max(...xs) + 40, Math.max(...ys) + 40,
  ]

  const pts = land.seeds.map((s) => [s.x, s.y] as Pt)
  const voronoi = Delaunay.from(pts).voronoi(bbox)

  land.seeds.forEach((seed: SeedDef, i: number) => {
    const cell = voronoi.cellPolygon(i)
    if (!cell) {
      problems.push(`no voronoi cell: ${seed.id}`)
      return
    }
    const cellPoly = (cell as Pt[]).slice(0, -1)
    const clipped = polygonClipping.intersection([[...cellPoly, cellPoly[0]] as any], [[...outline, outline[0]] as any])
    if (!clipped.length) {
      problems.push(`empty clip: ${seed.id}`)
      return
    }
    // keep the biggest ring
    let best: Pt[] = []
    for (const poly of clipped) {
      const ring = poly[0].slice(0, -1).map((p: number[]) => [Q(p[0]), Q(p[1])] as Pt)
      if (area(ring) > area(best)) best = ring
    }

    regions.push({
      id: seed.id,
      name: seed.name,
      terrain: seed.terrain,
      landmass: land.id,
      faction: seed.faction,
      landmark: seed.landmark,
      lostTribe: seed.lostTribe,
      mountain: seed.terrain === 'mountains',
      coastal: false,
      polygon: best,
      center: [Q(centroid(best)[0]), Q(centroid(best)[1])],
      neighbors: [],
    })

    for (let k = 0; k < best.length; k++) {
      const a = best[k]
      const b = best[(k + 1) % best.length]
      const ek = [key(a), key(b)].sort().join('|')
      const arr = edgeOwners.get(ek) ?? []
      arr.push(seed.id)
      edgeOwners.set(ek, arr)
    }
  })

  for (let k = 0; k < outline.length; k++) {
    const a = outline[k]
    const b = outline[(k + 1) % outline.length]
    coastKeys.add([key(a), key(b)].sort().join('|'))
  }
}

// adjacency + coastline detection
const byId = new Map(regions.map((r) => [r.id, r]))
for (const [ek, owners] of edgeOwners) {
  if (owners.length === 2) {
    const [a, b] = owners
    if (a === b) continue
    if (!byId.get(a)!.neighbors.includes(b)) byId.get(a)!.neighbors.push(b)
    if (!byId.get(b)!.neighbors.includes(a)) byId.get(b)!.neighbors.push(a)
  } else if (owners.length === 1) {
    // an edge with a single owner is on the boundary of the landmass -> coast
    byId.get(owners[0])!.coastal = true
  }
  if (coastKeys.has(ek)) owners.forEach((o) => (byId.get(o)!.coastal = true))
}

for (const r of regions) {
  if (r.neighbors.length === 0 && LANDMASSES.find((l) => l.id === r.landmass)!.seeds.length > 1) {
    problems.push(`isolated region on multi-seed landmass: ${r.id}`)
  }
  r.neighbors.sort()
}

const header = `// AUTO-GENERATED by scripts/genmap.ts \u2014 do not edit by hand.
import type { RegionData } from './types'

export const REGIONS: RegionData[] = `

writeFileSync(
  new URL('../src/game/mapData.generated.ts', import.meta.url),
  header + JSON.stringify(regions, null, 1) + '\n',
)

console.log(`regions: ${regions.length}`)
console.log(`coastal: ${regions.filter((r) => r.coastal).length}`)
console.log(`avg neighbours: ${(regions.reduce((s, r) => s + r.neighbors.length, 0) / regions.length).toFixed(2)}`)
console.log(problems.length ? 'PROBLEMS:\n' + problems.join('\n') : 'no problems')
